# Algorithm Configuration for Timeline Segmentation
# This file configures all algorithm parameters for the timeline segmentation system

detection_parameters:
  direction_change_threshold: 0.1
  direction_threshold_strategy: "global_p90"  # Options: "fixed", "global_p90", "global_p95", "global_p99"
  direction_scoring_method: "weighted_jaccard"  # Options: "weighted_jaccard", "jensen_shannon"
  min_baseline_period_years: 3
  score_distribution_window_years: 3
  citation_confidence_boost: 0.1
  citation_support_window_years: 2
  min_papers_per_year: 100

objective_function:
  cohesion_weight: 0.8
  separation_weight: 0.2
  top_k_keywords: 100
  min_keyword_frequency_ratio: 0.05

# Ubiquitous Keyword Filtering (De-generalization)
# Removes keywords that appear too frequently across all years to improve temporal discrimination
ubiquitous_filtering:
  apply_ubiquitous_filtering: true
  ubiquity_threshold: 0.8  # Keywords appearing in ≥80% of years are considered ubiquitous
  max_iterations: 10  # Maximum iterations to prevent infinite loops
  min_replacement_frequency: 2  # Minimum frequency for replacement keywords

beam_search:
  enabled: true
  beam_width: 5
  max_splits_per_segment: 1
  min_period_years: 5
  max_period_years: 50

diagnostics:
  save_direction_diagnostics: true
  diagnostic_top_keywords_limit: 10 