# Optimization Configuration for Timeline Segmentation
# Parameter ranges for Bayesian optimization
# 
# Note: Penalty and objective function parameters are loaded from config.yaml
# This file contains only optimization-specific configuration

# =============================================================================
# PARAMETER SEARCH SPACE
# =============================================================================

parameters:
  # Direction change detection parameters
  direction_change_threshold:
    type: float
    range: [0.6, 0.95]
    description: "Threshold for detecting significant direction changes"
  
  citation_confidence_boost:
    type: float
    range: [0.05, 0.2]
    description: "Boost factor for citation-based confidence"
  
  min_keyword_frequency_ratio:
    type: float
    range: [0.05, 0.15]
    description: "Minimum frequency ratio for keyword inclusion (data_processing.keyword_filter)"

  top_k_keywords:
    type: int
    range: [10, 30]
    description: "Number of top keywords to consider for period cohesion (data_processing.keyword_filter)"

# =============================================================================
# SEARCH STRATEGY
# =============================================================================

search:
  n_calls: 100
  n_initial_points: 20
  strategy: "bayesian"
  acquisition_function: "EI"

# =============================================================================
# OPTIMIZATION-SPECIFIC CONFIGURATION
# =============================================================================

# Scoring configuration
scoring:
  fail_score: -10.0
  boundary_tolerance: 2
  max_segments_per_match: 3

# Execution configuration
execution:
  max_workers: 8
  cache_academic_years: true 