parameters:
  # Uncomment to include in optimization
  direction_change_threshold:
    type: float
    range: [0.6, 0.95]
    description: "Threshold for detecting significant direction changes"

  # score_distribution_window_years:
  #   type: int
  #   range: [1, 5]
  #   description: "Window size in years for score distribution analysis"
  
  citation_confidence_boost:
    type: float
    range: [0.05, 0.2]
    description: "Boost factor for citation-based confidence"
  
  min_keyword_frequency_ratio:
    type: float
    range: [0.01, 0.1]
    description: "Minimum frequency ratio for keyword inclusion"

  # top_k_keywords:
  #   type: int
  #   range: [15, 100]
  #   description: "Number of top keywords for characterization"
  
  # min_baseline_period_years:
  #   type: int
  #   range: [2, 8]
  #   description: "Minimum baseline period for direction change detection"
  
  # citation_support_window_years:
  #   type: int
  #   range: [1, 5]
  #   description: "Window for citation support analysis"
  
  # cohesion_weight:
  #   type: float
  #   range: [0.3, 0.9]
  #   description: "Weight for cohesion in objective function"
  
  # separation_weight: 
  #   type: float
  #   range: [0.1, 0.7]
  #   description: "Weight for separation in objective function"
  
  # beam_width:
  #   type: int
  #   range: [3, 10]
  #   description: "Beam search width for refinement"
  
  # min_period_years:
  #   type: int
  #   range: [2, 8]
  #   description: "Minimum period length in years"
  
  # max_period_years:
  #   type: int
  #   range: [20, 100]
  #   description: "Maximum period length in years"

# Search Configuration
search:
  n_calls: 100  # Number of optimization trials
  n_initial_points: 20  # Number of random points before optimization starts (~10-20% of n_calls)
  strategy: "bayesian"
  acquisition_function: "EI"

# Penalty Configuration  
penalty:
  # Hybrid penalty combines over-segmentation and short-period penalties
  type: hybrid            # [linear | hybrid]
  # Over-segmentation component
  target_segments_upper: 8      # No cost if segments ≤ this value
  penalty_weight_over: 0.05     # Cost per extra segment beyond upper bound
  # Short-period component
  min_period_years: 5           # Minimum acceptable period length (years)
  short_period_weight: 0.02     # Cost per missing year below min_period_years
  # Long-period component
  max_period_years: 30          # Maximum acceptable period length
  long_period_weight: 0.02      # Cost per extra year beyond max_period_years
  # Legacy linear parameters (still respected if type: linear )
  target_segments: 6
  penalty_weight: 0.03

# Scoring Configuration
scoring:
  fail_score: -10.0       # Score assigned to failed trials
  boundary_tolerance: 2
  max_segments_per_match: 3

# Execution
execution:
  max_workers: 8
  cache_academic_years: true 